version: '3.8'
services:
  front:
    build: ./public
    ports:
      - 3000:3000
    volumes:
      - ./public/src:/app/src
      - /app/node_modules
    environment:
      - REACT_APP_LOCALHOST_KEY=chat-app-current-user
    networks:
      - chat-shared-network

  api:
    build: ./server
    depends_on:
      - mongo_svc
    ports:
      - 3322:3322
    environment:
      - MONGO_URL=mongodb://mongo_svc:27017/chat
    networks:
      - chat-shared-network

  mongo_svc:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - chatdbdata:/data/db
    networks:
      - chat-shared-network


volumes:
  chatdbdata:

networks:
  chat-shared-network:
    driver: bridge
